#!/usr/bin/env bash
# Show the  information regarding subdomains.

info_domain() {
    result=$(dig +short "$2"."$1")
    if [ -z "$result" ]; then
        echo "No information found for $2.$1"
    else
        echo "The subdomain $2 is a A record and points to $result"
    fi
}

# Main script
if [ "$#" -eq 1 ]; then
    domain="$1"
    info_domain "$domain" "www"
    info_domain "$domain" "lb-01"
    info_domain "$domain" "web-01"
    info_domain "$domain" "web-02"
elif [ "$#" -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    info_domain "$domain" "$subdomain"
fi
