#!/usr/bin/env bash
# custom err

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/eMode18 permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replacement="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s#listen 80 default_server;#$replacement#" /etc/nginx/sites-enabled/default


sudo service nginx restart

