#!/usr/bin/env bash
# Prints "To infinity and beyond" indefinitely
# Says "I am invincible!!!" in between iterations.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
