#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number (range 1-100)

for val in {1..100}
do
  if (( val % 3 == 0 && val % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( val % 3 == 0 ))
  then
    echo "Fizz"
  elif (( val % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$val"
  fi
done
