#!/usr/bin/env bash
# Script showcasing how to install and setup ufw firewall

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw status verbose
sudo ufw enable
sudo ufw status verbose
